{% set version = "1.3.10" %}

package:
  name: serf
  version: {{ version }}

source:
  fn:  serf-{{ version }}.tar.bz2
  url: https://archive.apache.org/dist/serf/serf-{{ version }}.tar.bz2
  sha256: be81ef08baa2516ecda76a77adf7def7bc3227eeb578b9a33b45f7b41dc064e6
  patches:
    - SConstruct.diff

build:
  number: 0
  # libapr and libaprutil are not availale n these platforms (as of August 2023).
  skip: True # [s390x or aarch64]
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/serf/
    # They keep changing soname b/w patch versions :'(
    - {{ pin_subpackage('serf', max_pin='x.x') }}
  ignore_run_exports:
    - expat

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - libapr
    - libaprutil
    - openssl {{ openssl }}
    - scons
    - zlib
    - expat
  run:
    - libapr
    - libaprutil
    - openssl # pin handled through openssl run_exports

  build:
    - {{ compiler('c') }}
    - cmake       # [win]

  # run_exports will take care of these
  # run:
    # - apr
    # - expat
    # - openssl
    # - zlib

test:
  commands:
    - if not exist %LIBRARY_INC%\serf.h     exit 1  # [win]
    - if not exist %LIBRARY_BIN%\serf-1.dll exit 1  # [win]

    - test -f ${PREFIX}/include/serf-1/serf.h       # [unix]
    - test -f ${PREFIX}/lib/libserf-1${SHLIB_EXT}   # [unix]


about:
  home: https://serf.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: High performance C-based HTTP client library
  description: |
    Serf is a simple web server. It is a development tool to be used during the
    development of rich internet applications.It is not intended for deployment.
  doc_url: https://serf.apache.org/
  dev_url: https://serf.apache.org/contribute
